
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using CrossOverStock.Data.Domain.Entity;

namespace CrossOverStock.Data.Domain
{


public partial class StockContext : DbContext
{
	public StockContext()
        : base(Helper.EntityHelper.ConnectionStringBuilder("Domain.StockContext", System.Configuration.ConfigurationManager.ConnectionStrings["StockContext"].ConnectionString)) { }
    public StockContext(string nameOrConnectionString)
        : base(nameOrConnectionString)
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<StockCode> StockCodes { get; set; }

    public virtual DbSet<UserStockCode> UserStockCodes { get; set; }

	
}


}
namespace CrossOverStock.Data.Domain.Repository
{

	public partial class StockCodeRepository : BaseRepository<StockCode>, Contract.IStockCodeRepository
	{
		public StockCodeRepository(StockContext dbContext, ICurrentUser currentUser) : base(dbContext, currentUser) { }
	}

	public partial class UserStockCodeRepository : BaseRepository<UserStockCode>, Contract.IUserStockCodeRepository
	{
		public UserStockCodeRepository(StockContext dbContext, ICurrentUser currentUser) : base(dbContext, currentUser) { }
	}

}
namespace CrossOverStock.Data.Domain.Repository.Contract
{

	public partial interface IStockCodeRepository : IRepository<StockCode> {	}	

	public partial interface IUserStockCodeRepository : IRepository<UserStockCode> {	}	



}

