//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossOverStock.Data.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStockCode : BaseEntity
    {
    
    public int FK_StockCodeId { get; set; }

    public int FK_UserId { get; set; }

		[System.ComponentModel.DataAnnotations.Schema.NotMapped]
            public override System.Boolean IsDeleted { get; set; }

		[System.ComponentModel.DataAnnotations.Schema.NotMapped]
            public override System.DateTime CreatedOnDate { get; set; }

		[System.ComponentModel.DataAnnotations.Schema.NotMapped]
            public override System.Int32 CreatedByUserId { get; set; }

		[System.ComponentModel.DataAnnotations.Schema.NotMapped]
            public override System.DateTime LastModifiedOnDate { get; set; }

		[System.ComponentModel.DataAnnotations.Schema.NotMapped]
            public override System.Int32 LastModifiedByUserId { get; set; }

        public virtual StockCode StockCode { get; set; }
    }
}
